USE QLDA
GO

-- PHONGBAN c1
SELECT * FROM dbo.PHONGBAN;

-- NHANVIEN c2
SELECT*FROM dbo.NHANVIEN;

-- CONGVIEC c3
SELECT * FROM dbo.CONGVIEC;

-- NHANVIEN and PHONGBAN c4
SELECT MANV, CONCAT(HONV,' ', TENNV) AS hoten, NGSINH, DCHI, MAPHG, TENPHG, TRPHG
FROM dbo.NHANVIEN INNER JOIN dbo.PHONGBAN 
ON PHONGBAN.MAPHG = NHANVIEN.PHG;

-- c5:
SELECT MANV, CONCAT(HONV,' ', TENNV) AS hoten, NGSINH, DCHI, MAPHG, TENPHG, TRPHG
FROM dbo.NHANVIEN INNER JOIN dbo.PHONGBAN 
ON PHONGBAN.MAPHG = NHANVIEN.PHG
WHERE TENPHG LIKE N'%Nghiên Cứu%'

-- c6:
SELECT MANV, CONCAT(HONV,' ', TENNV) AS hoten, MAPHG, THOIGIAN, TEN_CONG_VIEC
FROM dbo.NHANVIEN INNER JOIN dbo.PHANCONG ON PHANCONG.MA_NVIEN = NHANVIEN.MANV
				  INNER JOIN dbo.CONGVIEC ON CONGVIEC.MADA = PHANCONG.MADA
				  INNER JOIN dbo.PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
-- c7:

SELECT MANV, CONCAT(HONV,' ', TENNV) AS hoten, MAPHG, THOIGIAN, TEN_CONG_VIEC
FROM dbo.NHANVIEN INNER JOIN dbo.PHANCONG ON PHANCONG.MA_NVIEN = NHANVIEN.MANV
				  INNER JOIN dbo.CONGVIEC ON CONGVIEC.MADA = PHANCONG.MADA
				  INNER JOIN dbo.PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
WHERE TENPHG LIKE N'Điều Hành'

-- c8:
SELECT MAPHG, TENPHG, SUM(MADA) AS N'tổng số đề án'
FROM dbo.PHONGBAN LEFT OUTER JOIN dbo.DEAN ON DEAN.PHONG = PHONGBAN.MAPHG
GROUP BY MAPHG, TENPHG

-- c9:
SELECT MAPHG, TENPHG, SUM(MADA) AS N'tổng số đề án'
FROM dbo.PHONGBAN RIGHT OUTER JOIN dbo.DEAN ON DEAN.PHONG = PHONGBAN.MAPHG
GROUP BY MAPHG, TENPHG

-- c10:
SELECT MAPHG, TENPHG
FROM dbo.PHONGBAN LEFT OUTER JOIN dbo.DEAN ON DEAN.PHONG = PHONGBAN.MAPHG
WHERE MAPHG = 0;

-- c11:
SELECT MAPHG, TENPHG, COUNT(MANV) AS N'sô nhân viên'
FROM dbo.NHANVIEN RIGHT OUTER JOIN dbo.PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
GROUP BY MAPHG, TENPHG

-- c12:
ALTER TABLE dbo.NHANVIEN
ADD QUOCTICH NVARCHAR(30) NULL

-- c13:
UPDATE dbo.NHANVIEN 
SET PHAI = N'Nam'
WHERE MANV like '%002%'

-- c14:
UPDATE dbo.THANNHAN
SET QUANHE = N'Vợ'
WHERE MA_NVIEN LIKE '%017%'

SELECT*FROM dbo.THANNHAN


-- c15:
SELECT TOP 1 *
FROM dbo.NHANVIEN
ORDER BY LUONG DESC

-- c16:
SELECT AVG(LUONG) AS LuongTB 
FROM dbo.NHANVIEN

