CREATE DATABASE VUDD_PH14036
GO
USE VUDD_PH14036
GO

IF OBJECT_ID('CONGTO') IS NOT NULL
	DROP TABLE CONGTO
GO
CREATE TABLE CONGTO
(
	MACT VARCHAR(10) NOT NULL PRIMARY KEY(MACT),
	TENCT NVARCHAR(40) NULL
)
GO

IF OBJECT_ID('HOADON') IS NOT NULL
	DROP TABLE HOADON
GO
CREATE TABLE HOADON
(
	MAHD VARCHAR(10) NOT NULL PRIMARY KEY(MAHD),
	MACT VARCHAR(10) NOT NULL,
	SOCU INT  NULL CHECK (SOCU < SOMOI),
	SOMOI INT NULL,
	THANG INT NULL CHECK (THANG <= 12 AND THANG > 0),
	NAM INT NULL CHECK (NAM > 0),
	NGAYGHICT INT NULL CHECK (NGAYGHICT > 0 AND NGAYGHICT < 31),
	CONSTRAINT FK_HD_CT FOREIGN KEY(MACT) REFERENCES dbo.CONGTO
	
)
GO

INSERT dbo.CONGTO
			VALUES
			(   'CT',  -- MACT - varchar(10)
				N'ĐẶNG ĐÌNH VŨ' -- TENCT - nvarchar(40)
				)
GO

INSERT dbo.HOADON
		VALUES
		(   'HD',   -- MAHD - varchar(10)
			'CT',   -- MACT - varchar(10)
			123, -- SOCU - int
			652002, -- SOMOI - int
			1, -- THANG - datetime
			2002, -- NAM - datetime
			12  -- NGAYGHICT - datetime
			)
GO

SELECT*FROM dbo.CONGTO
SELECT*FROM dbo.HOADON


--C2:
IF OBJECT_ID('SP_BAI2') IS NOT NULL
	DROP PROC SP_BAI2
GO
CREATE PROC SP_BAI2
	@MACT VARCHAR(10), @TENCT NVARCHAR(30)
AS
	IF((@MACT IS NULL) AND (@TENCT IS NULL))
		BEGIN
			PRINT N'KHÔNG ĐƯỢC ĐỂ NULL'
		END
	ELSE
	BEGIN
	    INSERT dbo.CONGTO
			VALUES
			(   @MACT,  -- MACT - varchar(10)
				@TENCT -- TENCT - nvarchar(40)
				)
				PRINT N'THÊM THÀNH CÔNG'
	END
	
---GỌI
EXEC dbo.SP_BAI2 @MACT = 'CT2',  -- varchar(10)
                 @TENCT = N'NGUYỄN VĂN ĐỨC' -- nvarchar(30)

EXEC dbo.SP_BAI2 @MACT = 'CT3',  -- varchar(10)
                 @TENCT = N'NGUYỄN THỊ LAN' -- nvarchar(30)

--- HOA DON
IF OBJECT_ID('SP_BAI2A') IS NOT NULL
	DROP PROC SP_BAI2A
GO
CREATE PROC SP_BAI2A
	@MAHD VARCHAR(10), @MACT VARCHAR(10), @SOCU INT, @SOMOI INT, @THANG INT, @NAM INT, @NGAYGHICT INT
AS
IF((@MAHD IS NULL) AND (@MACT IS NULL) AND (@SOCU IS NULL) AND (@SOMOI IS NULL) 
AND (@THANG IS NULL) AND (@NAM IS NULL) AND (@NGAYGHICT IS NULL))
	BEGIN
		PRINT N'KHONG DUOC DE NULL'
	END
ELSE
	BEGIN
	INSERT dbo.HOADON
				VALUES
				(   @MAHD,   -- MAHD - varchar(10)
					@MACT,   -- MACT - varchar(10)
					@SOCU, -- SOCU - int
					@SOMOI, -- SOMOI - int
					@THANG, -- THANG - int
					@NAM, -- NAM - int
					@NGAYGHICT  -- NGAYGHICT - int
					)
	    PRINT N'THÊM THÀNH CÔNG'
	END
-- GOIJ
EXEC dbo.SP_BAI2A @MAHD = 'HD1',    -- varchar(10)
                  @MACT = 'CT',    -- varchar(10)
                  @SOCU = 1,     -- int
                  @SOMOI = 66,    -- int
                  @THANG = 1,    -- int
                  @NAM = 2002,      -- int
                  @NGAYGHICT = 1 -- int

EXEC dbo.SP_BAI2A @MAHD = 'HD2',    -- varchar(10)
                  @MACT = 'CT',    -- varchar(10)
                  @SOCU = 5,     -- int
                  @SOMOI = 80,    -- int
                  @THANG = 1,    -- int
                  @NAM = 2002,      -- int
                  @NGAYGHICT = 1 -- int
SELECT*FROM dbo.HOADON

-- C3:
IF OBJECT_ID('SP_BAI3') IS NOT NULL
	DROP FUNCTION SP_BAI3
GO
CREATE FUNCTION SP_BAI3
	(@MAHD VARCHAR(10))
RETURNS @HT TABLE (MAHD VARCHAR(10), TENCT NVARCHAR(30), THANG INT, NAM INT, SOCU INT, SOMOI INT, SODIENTIEUTHU INT)
AS
	BEGIN
	    INSERT @HT
			SELECT MAHD, TENCT, THANG, NAM, SOCU, SOMOI, (SOMOI - SOCU)
			FROM dbo.CONGTO JOIN dbo.HOADON ON HOADON.MACT = CONGTO.MACT
			WHERE MAHD = @MAHD
			RETURN
	END
GO
SELECT*FROM dbo.SP_BAI3('HD')

--C4:
IF OBJECT_ID('SP_Bai4') IS NOT NULL
	DROP PROC SP_Bai4
GO
CREATE PROC SP_Bai4
	@MACT VARCHAR(10)
AS
	BEGIN TRY
		BEGIN TRAN
			DELETE FROM dbo.HOADON
				WHERE MACT IN (SELECT MACT FROM dbo.HOADON WHERE MACT = @MACT)
			DELETE FROM dbo.CONGTO
				WHERE MACT IN (SELECT MACT FROM dbo.CONGTO WHERE MACT = @MACT)
				PRINT 'XOÁ THÀNH CÔNG!!!'
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		PRINT 'XOÁ KO THÀNH CÔNG';
	END CATCH
--GỌI
EXEC dbo.SP_Bai4 @MACT = 'CT' -- varchar(10)

SELECT*FROM dbo.CONGTO
SELECT*FROM dbo.HOADON

-- C5:
IF OBJECT_ID('SP_Bai5') IS NOT NULL
	DROP VIEW SP_Bai5
GO
CREATE VIEW SP_Bai5
AS
	SELECT DISTINCT CONGTO.MACT, TENCT, SOCU, SOMOI, (SOMOI-SOCU) AS SODIENTIEUTHU,
		IIF((SOMOI -SOCU) > 200, N'DÙNG NHIỀU', N'DÙNG ÍT') AS TRANGTHAI
	FROM dbo.CONGTO JOIN dbo.HOADON ON HOADON.MACT = CONGTO.MACT
GO
SELECT*FROM SP_Bai5