CREATE DATABASE DETAINGHIENCUU
GO

USE DETAINGHIENCUU
GO
IF OBJECT_ID('DETAI') IS NOT NULL
	DROP TABLE DETAI
GO
CREATE TABLE DETAI
(
	MADT VARCHAR(15) NOT NULL PRIMARY KEY(MADT),
	TENDT NVARCHAR(40) NULL,
	NAMTHUCHIEN INT
)
GO

IF OBJECT_ID('GIAOVIEN') IS NOT NULL
	DROP TABLE GIAOVIEN
GO
CREATE TABLE GIAOVIEN
(
	MAGV VARCHAR(15) NOT NULL PRIMARY KEY(MAGV),
	HOTEN NVARCHAR(40) NULL,
	NGSINH DATETIME,
	GIOITINH NVARCHAR(5) NULL,
)
GO

IF OBJECT_ID('THAMGIADETAI') IS NOT NULL
	DROP TABLE THAMGIADETAI
GO
CREATE TABLE THAMGIADETAI
(
	MAGV VARCHAR(15) NOT NULL PRIMARY KEY(MAGV, MADT),
	MADT VARCHAR(15) NOT NULL,
	PHUCAP MONEY NULL,
	FOREIGN KEY(MAGV) REFERENCES dbo.GIAOVIEN,
	FOREIGN KEY(MADT) REFERENCES dbo.DETAI
)
GO

--- C2:
IF OBJECT_ID('SP_BAI2') IS NOT NULL
	DROP PROC SP_BAI2
GO
CREATE PROC SP_BAI2
	@MADT VARCHAR(15), @TENDT NVARCHAR(40), @NAMTHUCHIEN INT
AS
	IF(@MADT IS NULL AND @TENDT IS NULL AND @NAMTHUCHIEN IS NULL)
	BEGIN
	    PRINT 'THEM K THANH CONG'
	END
ELSE
	BEGIN
	    INSERT dbo.DETAI
	    VALUES
	    (   @MADT,  -- MADT - varchar(15)
	        @TENDT, -- TENDT - nvarchar(40)
	        @NAMTHUCHIEN    -- NAMTHUCHIEN - int
	        )
	END
GO
EXEC dbo.SP_BAI2 @MADT = 'DT1',      -- varchar(15)
                 @TENDT = N'THIẾT KẾ SQL',    -- nvarchar(40)
                 @NAMTHUCHIEN = 2021 -- int

EXEC dbo.SP_BAI2 @MADT = 'DT2',      -- varchar(15)
                 @TENDT = N'THIẾT KẾ WEB',    -- nvarchar(40)
                 @NAMTHUCHIEN = 2021 -- int

EXEC dbo.SP_BAI2 @MADT = 'DT3',      -- varchar(15)
                 @TENDT = N'THIẾT KẾ API',    -- nvarchar(40)
                 @NAMTHUCHIEN = 2021 -- int
-- GIÁO VIÊN
IF OBJECT_ID('SP_BAI21') IS NOT NULL
	DROP PROC SP_BAI21
GO
CREATE PROC SP_BAI21
	@MAGV VARCHAR(15), @HOTEN NVARCHAR(40), @NGAYSINH DATETIME, @GIOITINH NVARCHAR(5)
AS
	IF(@MAGV IS NULL AND @HOTEN IS NULL AND @NGAYSINH IS NULL AND @GIOITINH IS NULL)
	BEGIN
	    PRINT 'THEM K THANH CONG'
	END
ELSE
	BEGIN
	    INSERT dbo.GIAOVIEN

	    VALUES
	    (   @MAGV,        -- MAGV - varchar(15)
	        @HOTEN,       -- HOTEN - nvarchar(40)
	        @NGAYSINH, -- NGSINH - datetime
	        @GIOITINH       -- GIOITINH - nvarchar(5)
	        )
	END
EXEC dbo.SP_BAI21 @MAGV = 'GV1',                        -- varchar(15)
                  @HOTEN = N'ĐẶNG ĐÌNH VŨ',                      -- nvarchar(40)
                  @NGAYSINH = '2002-05-06', -- datetime
                  @GIOITINH = N'NAM'                    -- nvarchar(5)

EXEC dbo.SP_BAI21 @MAGV = 'GV2',                        -- varchar(15)
                  @HOTEN = N'ĐẶNG ĐÌNH VŨ1',                      -- nvarchar(40)
                  @NGAYSINH = '2002-05-06', -- datetime
                  @GIOITINH = N'NAM'                    -- nvarchar(5)

EXEC dbo.SP_BAI21 @MAGV = 'GV3',                        -- varchar(15)
                  @HOTEN = N'ĐẶNG ĐÌNH VŨ2',                      -- nvarchar(40)
                  @NGAYSINH = '2002-05-06', -- datetime
                  @GIOITINH = N'NAM'                    -- nvarchar(5)

-- THAM GIA ĐỀ TÀI
IF OBJECT_ID('SP_BAI22') IS NOT NULL
	DROP PROC SP_BAI22
GO
CREATE PROC SP_BAI22
	@MAGV VARCHAR(15), @MADT VARCHAR(15), @PHUCAP FLOAT
AS
IF (@MAGV IS NULL AND @MADT IS NULL AND @PHUCAP IS NULL)
	BEGIN
	    PRINT'THEM K THANH CONG'
	END
ELSE 
	BEGIN
	    INSERT dbo.THAMGIADETAI

	    VALUES
	    (   @MAGV, -- MAGV - varchar(15)
	        @MADT, -- MADT - varchar(15)
	        @PHUCAP -- PHUCAP - float
	        )
	END
EXEC dbo.SP_BAI22 @MAGV = 'GV1',   -- varchar(15)
                  @MADT = 'DT1',   -- varchar(15)
                  @PHUCAP = 10000 -- float

EXEC dbo.SP_BAI22 @MAGV = 'GV2',   -- varchar(15)
                  @MADT = 'DT2',   -- varchar(15)
                  @PHUCAP = 20000 -- float

EXEC dbo.SP_BAI22 @MAGV = 'GV3',   -- varchar(15)
                  @MADT = 'DT3',   -- varchar(15)
                  @PHUCAP = 30000 -- float


--C3:
IF OBJECT_ID('SP_BAI3') IS NOT NULL
	DROP FUNCTION SP_BAI3
GO
CREATE FUNCTION SP_BAI3
	(@MAGV VARCHAR(15), @HTEN NVARCHAR(40), @NGAYSINH DATETIME, @GIOITINH NVARCHAR(5))
RETURNS VARCHAR(15)
AS
	BEGIN
	    RETURN(SELECT MAGV FROM dbo.GIAOVIEN 
		WHERE MAGV = @MAGV AND HOTEN = @HTEN AND NGSINH = @NGAYSINH AND GIOITINH = @GIOITINH)
	END
GO
DECLARE @MAGV VARCHAR(15)
SET @MAGV = dbo.SP_BAI3('GV1', N'ĐẶNG ĐÌNH VŨ', '2002-05-06', N'NAM');
SELECT @MAGV AS MAGV

-- C4
IF OBJECT_ID('SP_BAI4') IS NOT NULL
	DROP VIEW SP_BAI4
GO
CREATE VIEW SP_BAI4
AS
	SELECT TOP 2 GIAOVIEN.MAGV, HOTEN, SUM(PHUCAP) AS TONGPHUCAP 
	FROM dbo.GIAOVIEN JOIN dbo.THAMGIADETAI ON THAMGIADETAI.MAGV = GIAOVIEN.MAGV
	GROUP BY GIAOVIEN.MAGV, HOTEN
	ORDER BY TONGPHUCAP DESC
GO
SELECT*FROM dbo.SP_BAI4

-- C5
IF OBJECT_ID('SP_BAI5') IS NOT NULL
	DROP PROC SP_BAI5
GO
CREATE PROC SP_BAI5
  @TONGTIEN MONEY
AS
	BEGIN TRY
		BEGIN TRAN
			DECLARE @TABLE TABLE (MAGV NVARCHAR(15), PHUCAP MONEY)
			INSERT @TABLE
						SELECT GIAOVIEN.MAGV, SUM(PHUCAP) AS TONGTIEN
						FROM dbo.GIAOVIEN JOIN dbo.THAMGIADETAI ON THAMGIADETAI.MAGV = GIAOVIEN.MAGV
						GROUP BY GIAOVIEN.MAGV
						HAVING SUM(PHUCAP) > @TONGTIEN
			DELETE dbo.THAMGIADETAI WHERE MAGV IN (SELECT MAGV FROM @TABLE)
			DELETE dbo.GIAOVIEN WHERE MAGV IN (SELECT MAGV FROM @TABLE)
			PRINT'THEM THANH CONG'
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		PRINT'ERROR!!!!'
	END CATCH
GO
--GỌI
EXEC dbo.SP_BAI5 @TONGTIEN = 1000 -- money

SELECT*FROM dbo.GIAOVIEN
SELECT*FROM dbo.THAMGIADETAI
SELECT*FROM dbo.DETAI

