USE QLDA

-- BAI 1: SỬ DỤNG BIẾN VÔ HƯỚNG
DECLARE @LTB FLOAT
SELECT @LTB = AVG(LUONG) 
FROM NHANVIEN JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
WHERE TENPHG = N'NGHIÊN CỨU'
SELECT @LTB

-- BAI 3: SỬ DỤNG BIẾN BẢNG
DECLARE @BIENBANG TABLE (MANV INT, TENNV NVARCHAR(30), DCHI NVARCHAR(50), LUONG FLOAT)
INSERT INTO @BIENBANG
SELECT MANV, TENNV, DCHI, LUONG FROM NHANVIEN JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
WHERE TENPHG LIKE N'Nghiên Cứu'
SELECT * FROM @BIENBANG

-- BAI 2: SỬ DỤNG BIẾN VÔ HƯỚNG
DECLARE @A INT, @B INT;
SET @A = 12;
SET @B = 5;

WHILE @A != @B
BEGIN
	IF(@A >@B)
	SET @A -= @B

	ELSE
	SET @B -= @A
END
SELECT @A AS N'ƯỚC CHUNG LỚN NHẤT';