use QLDA
go
--Lab1
--1
SELECT * FROM NHANVIEN
WHERE PHG = 4;

--2
SELECT * FROM NHANVIEN
WHERE LUONG > 30000

--3
SELECT * FROM NHANVIEN
WHERE (LUONG > 25000 AND PHG = 4) OR (LUONG > 30000 AND PHG = 5)

--4
SELECT HONV +' '+TENLOT+' ' +TENNV AS N'HovaTen'FROM NHANVIEN
WHERE DCHI LIKE '%HCM%'

--5
SELECT HONV +' '+TENLOT+' ' +TENNV AS N'HovaTen'FROM NHANVIEN
WHERE HONV LIKE 'N%'

--6
SELECT NGSINH,DCHI FROM NHANVIEN
WHERE HONV = N'Ðinh' AND TENLOT = N'Bá' AND TENNV = N'Tiên'

