use QLDA
go
--Lab3
--1

--kiểu decimal của số giờ làm việc
DECLARE @CAST table(TenDA NVARCHAR(30), TGLV FLOAT)
INSERT INTO @CAST
SELECT DEAN.TENDEAN, CAST(SUM(PHANCONG.THOIGIAN)AS decimal(5,2)) FROM DEAN
INNER JOIN CONGVIEC ON DEAN.MADA = CONGVIEC.MADA
INNER JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY DEAN.TENDEAN
SELECT * FROM @CAST

--kiểu varchar của số giờ làm việc
DECLARE @CONVERT table(TenDA NVARCHAR(30), TGLV FLOAT)
INSERT INTO @CONVERT
SELECT DEAN.TENDEAN, CONVERT(VARCHAR,SUM(PHANCONG.THOIGIAN)) FROM DEAN
INNER JOIN CONGVIEC ON DEAN.MADA = CONGVIEC.MADA
INNER JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY DEAN.TENDEAN
SELECT * FROM @CONVERT

--kiểu decimal của tên phòng ban và lương trung bình
DECLARE @LUONGTB TABLE(TENPB NVARCHAR(30), LUONG FLOAT)
INSERT INTO @LUONGTB
SELECT PHONGBAN.TENPHG,CAST(AVG(NHANVIEN.LUONG) AS DECIMAL(7,2)) AS 'LuongTB'FROM NHANVIEN
INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
GROUP BY PHONGBAN.TENPHG
SELECT * FROM @LUONGTB

--kiểu varchar của tên phòng ban và lương trung bình
DECLARE @LUONG TABLE(TENPB NVARCHAR(30), LUONGTB FLOAT)
INSERT INTO @LUONG
SELECT PHONGBAN.TENPHG, REPLACE(AVG(NHANVIEN.LUONG),LEFT(AVG(NHANVIEN.LUONG),3),',') AS 'LuongTB'FROM NHANVIEN
INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
GROUP BY PHONGBAN.TENPHG

SELECT * FROM @LUONG

--2
-- Xuất định dạng “tổng số giờ làm việc” với hàm CEILING
DECLARE @CEILING table(TenDA NVARCHAR(30), TGLV FLOAT)
INSERT INTO @CEILING
SELECT DEAN.TENDEAN, CEILING(SUM(PHANCONG.THOIGIAN)) FROM DEAN
INNER JOIN CONGVIEC ON DEAN.MADA = CONGVIEC.MADA
INNER JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY DEAN.TENDEAN
SELECT * FROM @CEILING

--Xuất định dạng “tổng số giờ làm việc” với hàm FLOOR
DECLARE @FLOOR table(TenDA NVARCHAR(30), TGLV FLOAT)
INSERT INTO @FLOOR
SELECT DEAN.TENDEAN, FLOOR(SUM(PHANCONG.THOIGIAN)) FROM DEAN
INNER JOIN CONGVIEC ON DEAN.MADA = CONGVIEC.MADA
INNER JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY DEAN.TENDEAN
SELECT * FROM @FLOOR

--Xuất định dạng “tổng số giờ làm việc” làm tròn tới 2 chữ số thập phân
DECLARE @ROUND table(TenDA NVARCHAR(30), TGLV FLOAT)
INSERT INTO @ROUND
SELECT DEAN.TENDEAN, ROUND(SUM(PHANCONG.THOIGIAN),2) FROM DEAN
INNER JOIN CONGVIEC ON DEAN.MADA = CONGVIEC.MADA
INNER JOIN PHANCONG ON PHANCONG.MADA = CONGVIEC.MADA
GROUP BY DEAN.TENDEAN
SELECT * FROM @ROUND

--Cho biết họ tên nhân viên (HONV, TENLOT, TENNV) có mức lương trên mức lương


--trung bình (làm tròn đến 2 số thập phân) của phòng "Nghiên cứu"
SELECT * FROM NHANVIEN
SELECT * FROM PHONGBAN
SELECT NHANVIEN.HONV, NHANVIEN.TENLOT, NHANVIEN.TENNV FROM NHANVIEN
WHERE LUONG > (
	SELECT ROUND(AVG(NHANVIEN.LUONG),2) FROM NHANVIEN
	INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
	WHERE TENPHG = N'Nghiên Cứu'
)
--3
--Dữ liệu cột HONV được viết in hoa toàn bộ

SELECT UPPER(NHANVIEN.HONV) AS 'HONV', LOWER(NHANVIEN.TENLOT) AS 'TENLOT',
REPLACE(LOWER(NHANVIEN.TENNV),SUBSTRING(NHANVIEN.TENNV,2,1),UPPER(SUBSTRING(NHANVIEN.TENNV,2,1))) AS'TENNV',
NHANVIEN.DCHI, LTRIM(NHANVIEN.DCHI) FROM NHANVIEN
INNER JOIN THANNHAN ON NHANVIEN.MANV = THANNHAN.MA_NVIEN
GROUP BY NHANVIEN.HONV, NHANVIEN.TENLOT, NHANVIEN.TENNV, NHANVIEN.DCHI
HAVING COUNT(THANNHAN.MA_NVIEN) > 2

--Cho biết tên phòng ban và họ tên trưởng phòng của phòng ban có đông nhân viên nhất,


--hiển thị thêm một cột thay thế tên trưởng phòng bằng tên “Fpoly”
SELECT TOP 1 PHONGBAN.TENPHG, NHANVIEN.HONV + ' ' + NHANVIEN.TENLOT + ' ' + NHANVIEN.TENNV AS 'HOTEN', REPLACE(NHANVIEN.TENNV,NHANVIEN.TENNV,'FPOLY') FROM NHANVIEN
INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
WHERE PHONGBAN.TRPHG  = (
	SELECT TOP 1 NHANVIEN.MA_NQL FROM NHANVIEN
	GROUP BY NHANVIEN.MA_NQL
	ORDER BY COUNT(NHANVIEN.PHG) DESC
)
--4
--Cho biết các nhân viên có năm sinh trong khoảng 1960 đến 1965
SELECT * FROM NHANVIEN
WHERE YEAR(NHANVIEN.NGSINH) BETWEEN 1960 AND 1965

--Cho biết tuổi của các nhân viên tính đến thời điểm hiện tại.
SELECT * ,(YEAR(GETDATE()) - YEAR(NHANVIEN.NGSINH)) AS 'AGE' FROM NHANVIEN

-- Dựa vào dữ liệu NGSINH, cho biết nhân viên sinh vào thứ mấy.
SELECT *, DATEPART(WEEKDAY,NHANVIEN.NGSINH) AS 'thu' FROM NHANVIEN


