use QLDA
go
--Câu 1
	-- DÙNG CASE
	--1.1
	DECLARE @TBLUONG float
	SELECT @TBLUONG =  AVG(LUONG) FROM NHANVIEN
	SELECT TENNV, 
	'NHAN XET' = CASE
		WHEN LUONG < @TBLUONG THEN N'Tăng Lương'
		WHEN LUONG > @TBLUONG THEN N'Không Tăng Lương'
		END
	FROM NHANVIEN
	GROUP BY TENNV,LUONG

 --1.2
 DECLARE @TBLUONG1 float
	SELECT @TBLUONG1 =  AVG(LUONG) FROM NHANVIEN
	SELECT 'CHUC VU' = CASE 
		WHEN LUONG < @TBLUONG1 THEN N'Nhân Viên'
		WHEN LUONG > @TBLUONG1 THEN N'Trưởng Phòng'
		END, TENNV,LUONG
	FROM NHANVIEN
	GROUP BY TENNV,LUONG

-- 1.3
	SELECT TENNV = CASE PHAI
	WHEN 'Nam' Then 'Mr. ' + [TENNV]
	WHEN 'Nữ' Then 'Ms. ' + [TENNV]
	ELSE 'BEDE. ' + [TENNV]
	END
	FROM NHANVIEN

-- bai1:
FROM dbo.NHANVIEN
--1.4
	SELECT TENNV,LUONG, 
	'THUE' = CASE
		WHEN LUONG<25000 THEN LUONG*0.1
		WHEN LUONG<30000 THEN LUONG*0.12
		WHEN LUONG<40000 THEN LUONG*0.15
		WHEN LUONG<50000 THEN LUONG*0.2
		ELSE LUONG*0.25
		END
	FROM NHANVIEN

-- DÙNG IF..ELSE
--1.1	
DECLARE @TBLUONG FLOAT
	SELECT @TBLUONG = AVG(LUONG) FROM NHANVIEN
	SELECT IIF(LUONG<@TBLUONG,N'TĂNG LƯƠNG',N'KHÔNG TĂNG LƯƠNG ')
AS DANHGIA,TENNV,LUONG
	FROM NHANVIEN
	GROUP BY LUONG,TENNV
--1.2
DECLARE @TBLUONG1 FLOAT
	SELECT @TBLUONG1 = AVG(LUONG) FROM NHANVIEN
	SELECT IIF(LUONG<@TBLUONG1,N'NHÂN VIÊN',N'TRƯỞNG PHÒNG')
AS DANHGIA,TENNV,LUONG
	FROM NHANVIEN
	GROUP BY LUONG,TENNV
--1.3
DECLARE @a NVARCHAR(15),@b NVARCHAR(15)
SET @a = 'Mr. '
SET @b = 'Ms. '
SELECT IIF(PHAI = 'Nam',@a + TENNV, @b + TENNV)
AS TENNV
FROM dbo.NHANVIEN

--- lab4 bai1:
SELECT MANV, TENNV, PHAI AS gioiTinh, NGSINH, DATEDIFF(YEAR, NGSINH, GETDATE()) AS Tuoi,
	IIF(PHAI = N'Nam', 'Mr.' + TENNV,'Ms.'+ TENNV) AS TenNV,
	'Trạng Thái' = CASE
	WHEN DATEDIFF(YEAR, NGSINH, GETDATE()) < 18 THEN N'Trẻ em.'
	WHEN DATEDIFF(YEAR, NGSINH, GETDATE()) < 60 THEN N'Lao động.'
	ELSE N'Tuổi già.'
	END
FROM dbo.NHANVIEN

--- lab4 bai2:


-- Câu 2
--2.1
	DECLARE @dem int = 2;
	WHILE @dem<(SELECT COUNT(MANV) FROM NHANVIEN) 
		BEGIN
			SELECT HONV,TENLOT,TENNV,MANV FROM NHANVIEN
			WHERE CAST(MANV AS INT) = @dem 
			SET @dem = @dem + 2
		END 

--2.2
	DECLARE @INDEX int = 0;
	WHILE @INDEX<(SELECT COUNT(MANV) FROM NHANVIEN) 
		BEGIN
		SET  @INDEX= @INDEX + 2
		IF @INDEX = 4 CONTINUE
			SELECT HONV,TENLOT,TENNV,MANV FROM NHANVIEN
			WHERE CAST(MANV AS INT) = @INDEX 
		END 


--Câu 3
   -- 3.1
   select * from PHONGBAN
	BEGIN TRY
		INSERT PHONGBAN
		VALUES ('Tester',113,'006', '0197-05-22') --Thành công
		--VALUES ('Tester','11','006', '0197-05-22') --Sai
		PRINT N'Thêm dữ liệu thành công'
	END TRY

	BEGIN CATCH
	PRINT N'Thêm dữ liệu thất bại'
	END CATCH

	-- 3.2
	BEGIN TRY
		DECLARE @chia int
		SET @chia = 20/0
	END TRY
	BEGIN CATCH
	DECLARE
		@erMessage NVARCHAR(2000),
		@erSeverity INT,
		@erState INT
	SELECT 
	 @erMessage = ERROR_MESSAGE(),
	 @erSeverity = ERROR_SEVERITY(),
	 @erState = ERROR_STATE()
	RAISERROR (@erMessage,@erSeverity,@erState)
	END CATCH