CREATE DATABASE QLBH
GO

USE QLBH
GO

CREATE TABLE KHACHHANG(
	ID_KH INT IDENTITY NOT NULL,
	TEN_KH NVARCHAR(100) NOT NULL,
	PHONE NVARCHAR(11) NOT NULL
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(ID_KH)
)
GO

CREATE TABLE NHANVIEN(
	ID_NV INT IDENTITY(1,1) NOT NULL,
	TEN_NV NVARCHAR(100) NOT NULL,
	NGSINH DATE NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	GIOITINH NVARCHAR(5) NOT NULL,
	USERS NVARCHAR(50) NOT NULL,
	PASSWORDS NVARCHAR(50) NOT NULL,
	EMAIL NVARCHAR(200) NOT NULL,
	PHONE NVARCHAR(11) NOT NULL,
	CHUCVU NVARCHAR(20) NOT NULL,

	CONSTRAINT PK_NHANVIEN PRIMARY KEY(ID_NV)
)
GO
--SELECT * FROM SANPHAM
CREATE TABLE SANPHAM(
	ID_SP NVARCHAR(15) NOT NULL,
	TEN_SP NVARCHAR(50) NOT NULL,
	LOAI_SP NVARCHAR(50) NOT NULL,
	MAUSAC NVARCHAR(100) NOT NULL,
	SIZE INT NOT NULL,
	IMAGES NVARCHAR(100) NOT NULL,
	GIABAN MONEY NOT NULL,
	NGNHAP DATE NOT NULL,
	SOLUONG INT NOT NULL,
	TRANGTHAI NVARCHAR(50) NULL,

	CONSTRAINT PK_SANPHAM PRIMARY KEY(ID_SP)
)
GO

CREATE TABLE HOADON(
	ID_HD NVARCHAR(15) NOT NULL,
	ID_NV INT NOT NULL,
	ID_KH INT IDENTITY NOT NULL,
	NGMUA DATE NOT NULL,
	TONGTIEN MONEY NOT NULL,
	
	CONSTRAINT PK_HOADON PRIMARY KEY(ID_HD),
	CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY(ID_NV) REFERENCES NHANVIEN(ID_NV),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(ID_KH) REFERENCES KHACHHANG(ID_KH),

)
GO

CREATE TABLE HOADON_CHITIET(
	ID_HDCT INT IDENTITY NOT NULL,
	ID_HD NVARCHAR(15) NOT NULL,
	ID_SP NVARCHAR(15) NOT NULL,
	TEN_SP NVARCHAR(50)  NOT NULL,
	MAUSAC NVARCHAR(100) NOT NULL,
	SIZE INT NOT NULL,
	SOLUONG INT NOT NULL,
	NGAYMUA DATE NOT NULL,
	GIA MONEY NOT NULL,
	DISCOUNT FLOAT NOT NULL,
	THANHTIEN MONEY NOT NULL,

	CONSTRAINT PK_HOADON_CHITIET PRIMARY KEY(ID_HDCT),
	CONSTRAINT FK_HOADON_CHITIET_NHANVIEN FOREIGN KEY(ID_HD) REFERENCES HOADON(ID_HD),
	CONSTRAINT FK_INVOICE_DETAILS_SANPHAM FOREIGN KEY(ID_SP) REFERENCES SANPHAM(ID_SP)
)
GO

SELECT * FROM SANPHAM
SELECT DAY(NGMUA),TONGTIEN FROM HOADON

INSERT INTO SANPHAM
VALUES('MC02', 'MC Queen', N'Nearker', N'Trắng', 42, 'D:\download\mcqueen.jpg', 350000, '2020-07-27', 20, N'Chưa về')
INSERT INTO NHANVIEN
VALUES(N'Nguyễn Quang Khải', '2001-08-23', N'Nam Sách - Hải Dương', 'Nam', 'quangkhai2308', '23082001', 'khainqph12175@gmail.com', '0975395955', 'Admin')
INSERT INTO NHANVIEN
VALUES(N'Nguyễn Quang Khải', '2001-08-23', N'Nam Sách - Hải Dương', 'Nam', 'quangkhai2308', '23082001', 'khainqph12175@gmail.com', '0975395955', 'Admin')

INSERT INTO NHANVIEN
VALUES(N'Bùi Xuân Sáng', '2001-06-01', N'Nam Từ Liêm - Hà Nội', 'Nam', 'xuansang0106', '01062001', 'sangbxph12221@gmail.com', '0912345678', 'Admin')

INSERT INTO NHANVIEN
VALUES(N'Quân Việt Anh', '2001-10-20', N'Cầu Giấy - Hà Nội', 'Nam', 'vietanh2010', '20102001', 'anhqvph12132@gmail.com', '0993433456', 'Admin')
SELECT * FROM HOADON
SELECT * FROM HOADON_CHITIET