USE QLDA
GO
--Kiểm tra lượng nhân viên nhập vào phải từ 5000 trở lên
CREATE TRIGGER kt_luongNV_moi ON NHANVIEN
FOR INSERT 
AS
IF(SELECT LUONG FROM inserted) < 5000
		BEGIN
			PRINT('Tien luong toi thieu phai lon hon 5000')
		ROLLBACK TRANSACTION
	END
ELSE 
		PRINT('Ban da ghi thanh cong')
INSERT INTO NHANVIEN
VALUES (N'Kim', N'Thanh', N'Thế', N'038', '1967-02-01', N'291 Hồ Văn Huê, TP HCM', N'Nữ', 7000, N'005', 4)

--Khong duoc sua luong <5000
CREATE TRIGGER kt_khongsua_luong ON NHANVIEN
FOR UPDATE
AS
IF(SELECT LUONG FROM inserted) < 5000
	BEGIN
		PRINT('Tien luong toi thieu phai lon hon 5000')
		ROLLBACK TRANSACTION
	END
ELSE
		PRINT('OKE LA ')
	UPDATE NHANVIEN SET LUONG = 2000 WHERE MANV LIKE '005'

--khong duoc xoa nhan vien co ma nhan vien la 005

ALTER TRIGGER kt_khongxoa1 ON NHANVIEN
FOR DELETE
AS
IF (SELECT MANV FROM deleted) = '036'
	BEGIN
		PRINT('khong the xoa nhan vien co ma 036')
		ROLLBACK TRANSACTION
	END
ELSE	
	PRINT('OKE LA')
	DELETE NHANVIEN WHERE MANV LIKE '036'
	SELECT * FROM NHANVIEN

--vIET TRIGGER DEM SO LUONG NHAN VIEN BI XOA KHI CO CAU LENH XOA TREN BANG NHAN VIEN
CREATE TRIGGER Xoa_NV ON NHANVIEN
AFTER DELETE
AS
BEGIN
DECLARE @NUM nchar
SELECT @NUM = COUNT(*) FROM deleted
PRINT N'Số lượng nhân vien đã xóa = ' + @NUM
END
DELETE FROM NHANVIEN WHERE MANV = '038'
--XOA NHAN VIEN CO MA 017 CAC THAN NHAN CUA NV NAY TU DONG XOA THEO BANG THAN NHAN
CREATE TRIGGER Delete_NV_NT ON NHANVIEN
INSTEAD OF DELETE
AS
BEGIN
DELETE FROM THANNHAN WHERE MA_NVIEN IN
(SELECT MA_NVIEN FROM deleted)
DELETE FROM NHANVIEN WHERE MANV IN 
(SELECT MANV FROM deleted)
END

DELETE FROM NHANVIEN WHERE MANV LIKE '017'